"""empty message

Revision ID: df73efce94c
Revises: 44fc33f981bc
Create Date: 2015-06-28 00:55:15.158854

"""

# revision identifiers, used by Alembic.
revision = 'df73efce94c'
down_revision = '44fc33f981bc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
